title: iSpindel
description: DIY electronic Hydrometer
google_analytics: UA-114587576-1
google_ad_client: ca-pub-5402138770970422
show_downloads: true
theme: jekyll-theme-tactile

plugins:
  - jekyll-mentions
include: ['docs']
